
name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run:
        mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.11
      with:
        # The name of the image you would like to push
        name: w929732982/mall-test
        # The login username for the registry
        username: ${{secrets.DOCKERHUB_USERNAME}}
        # The login password for the registry
        password: ${{secrets.DOCKERHUB_PASSWORD}}

     
